name: Check Code Standard

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run_check_standard:
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.10', '3.13']
    uses: intel/mfd/.github/workflows/check_code_standard.yml@main  
    with:
      REPOSITORY_NAME: ${{ github.event.pull_request.head.repo.full_name }}
      BRANCH_NAME: ${{ github.head_ref }}
      PYTHON_VERSION: ${{ matrix.python_version }}