name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build_whl:
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.10', '3.13']
    uses: intel/mfd/.github/workflows/main.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      REPOSITORY_NAME: ${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      PROJECT_NAME: 'mfd-typing'
