name: CI Build - Release Mode

on:
  workflow_dispatch:

jobs:
  build_upload_whl:
    strategy:
      fail-fast: false
      matrix:
        include:
        - python_version: '3.10'
          release_steps: true
        - python_version: '3.13'
          release_steps: false
    uses: intel/mfd/.github/workflows/manual_release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      REPOSITORY_NAME: ${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      PROJECT_NAME: 'mfd-typing'
      RELEASE_STEPS: ${{ matrix.release_steps }}
