name: Dev Build

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build_whl:
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.10', '3.13']
    uses: intel/mfd/.github/workflows/pull_request.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      REPOSITORY_NAME: ${{ github.event.pull_request.head.repo.full_name }}
      BRANCH_NAME: ${{ github.head_ref }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      PROJECT_NAME: 'mfd-typing'